server:
  port: 8080
spring:
  config:
    import: optional:file:.env
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

    show-sql: true
  devtools:
    restart:
      enabled: true  # 자동 재시작 활성화
    livereload:
      enabled: true  # LiveReload 활성화

